FROM node:22-alpine
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@latest --activate
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --ignore-scripts --config.confirmModulesPurge=false
COPY . .
EXPOSE 3000
CMD ["node_modules/.bin/nest", "start", "--watch"]
